# Generated by Django 5.0.9 on 2024-12-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_post_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_car',
            name='p_foto',
            field=models.ImageField(blank=True, upload_to='imagens/'),
        ),
    ]
